platform :ios, '7.0'
pod 'AFNetworking', '~> 2.0'
pod 'NSURL+ParseQuery'
pod 'Loader'
pod 'DropdownMenu'
pod 'HexColors'
pod 'FontAwesomeKit/FontAwesome'
pod 'FontAwesomeKit/FoundationIcons'
pod 'NUI'
pod 'SDWebImage'
pod 'UIView+AutoLayout'
pod 'TTTAttributedLabel'
pod 'SVPullToRefresh'