platform :ios, '7.0'
pod 'AFNetworking', '~> 2.0'
pod 'NSURL+ParseQuery'
pod 'DropdownMenu'
pod 'HexColors'
pod 'FontAwesomeKit/FontAwesome'
pod 'FontAwesomeKit/FoundationIcons'
pod 'FontAwesomeKit/IonIcons'
pod 'NUI'
pod 'TTTAttributedLabel'
pod 'SVPullToRefresh'
pod 'SDWebImage'
pod 'TOWebViewController'
pod 'Mixpanel'
pod 'AHKActionSheet'
pod 'MFStoryboardPushSegue'
pod 'TPKeyboardAvoiding'
pod 'ALPValidator'
pod 'Canvas'